//go:build !noasm && amd64
// Code generated by gocc -- DO NOT EDIT.

package utf8


//go:noescape
func indexFoldAVX2(haystack string, needle string, metadata *indexFoldNeedleMetadata, matched_length *uint64) int
