//go:build !noasm && arm64
// Code generated by gocc -- DO NOT EDIT.

package utf8


//go:noescape
func indexFoldNeon(haystack string, needle string, metadata *indexFoldNeedleMetadata, matched_length *uint64) int
