//go:build !noasm && amd64
// Code generated by gocc v0.16.5-rev-57c4d32 -- DO NOT EDIT.
//
// Source file         : ascii_avx2.c
// Clang version       : Apple clang version 16.0.0 (clang-1600.0.26.6)
// Target architecture : amd64
// Compiler options    : -mavx2 -mfma

#include "textflag.h"

DATA LCPI0_0<>+0x00(SB)/8, $0x8080808080808080
GLOBL LCPI0_0<>(SB), (RODATA|NOPTR), $8

DATA LCPI0_1<>+0x00(SB)/8, $0x8080808080808080
DATA LCPI0_1<>+0x08(SB)/8, $0x8080808080808080
GLOBL LCPI0_1<>(SB), (RODATA|NOPTR), $16

TEXT ·isAsciiAvx(SB), NOSPLIT, $0-17
	MOVQ         src+0(FP), DI
	MOVQ         src_len+8(FP), SI
	NOP                              // (skipped)                            // push	rbp
	NOP                              // (skipped)                            // mov	rbp, rsp
	NOP                              // (skipped)                            // and	rsp, -8
	CMPQ         SI, $0x10           // <--                                  // cmp	rsi, 16
	JB           LBB0_13             // <--                                  // jb	.LBB0_13
	LEAQ         0(DI)(SI*1), CX     // <--                                  // lea	rcx, [rdi + rsi]
	WORD         $0xf089             // MOVL SI, AX                          // mov	eax, esi
	WORD         $0xe083; BYTE $0x7f // ANDL $0x7f, AX                       // and	eax, 127
	SUBQ         AX, CX              // <--                                  // sub	rcx, rax
	CMPQ         CX, DI              // <--                                  // cmp	rcx, rdi
	JBE          LBB0_5              // <--                                  // jbe	.LBB0_5
	VPBROADCASTQ LCPI0_0<>(SB), Y0   // <--                                  // vpbroadcastq	ymm0, qword ptr [rip + .LCPI0_0]

LBB0_3:
	LONG $0x4f6ffec5; BYTE $0x20 // VMOVDQU 0x20(DI), Y1                 // vmovdqu	ymm1, ymmword ptr [rdi + 32]
	LONG $0x0febf5c5             // VPOR 0(DI), Y1, Y1                   // vpor	ymm1, ymm1, ymmword ptr [rdi]
	LONG $0x4febf5c5; BYTE $0x40 // VPOR 0x40(DI), Y1, Y1                // vpor	ymm1, ymm1, ymmword ptr [rdi + 64]
	LONG $0x4febf5c5; BYTE $0x60 // VPOR 0x60(DI), Y1, Y1                // vpor	ymm1, ymm1, ymmword ptr [rdi + 96]
	LONG $0x177de2c4; BYTE $0xc8 // VPTEST Y0, Y1                        // vptest	ymm1, ymm0
	JNE  LBB0_19                 // <--                                  // jne	.LBB0_19
	SUBQ $-0x80, DI              // <--                                  // sub	rdi, -128
	CMPQ DI, CX                  // <--                                  // cmp	rdi, rcx
	JB   LBB0_3                  // <--                                  // jb	.LBB0_3

LBB0_5:
	ADDQ         DI, AX              // <--                                  // add	rax, rdi
	WORD         $0xf189             // MOVL SI, CX                          // mov	ecx, esi
	WORD         $0xe183; BYTE $0x1f // ANDL $0x1f, CX                       // and	ecx, 31
	SUBQ         CX, AX              // <--                                  // sub	rax, rcx
	CMPQ         DI, AX              // <--                                  // cmp	rdi, rax
	JAE          LBB0_9              // <--                                  // jae	.LBB0_9
	VPBROADCASTQ LCPI0_0<>(SB), Y0   // <--                                  // vpbroadcastq	ymm0, qword ptr [rip + .LCPI0_0]

LBB0_7:
	LONG $0x0f6ffec5             // VMOVDQU 0(DI), Y1                    // vmovdqu	ymm1, ymmword ptr [rdi]
	LONG $0x177de2c4; BYTE $0xc8 // VPTEST Y0, Y1                        // vptest	ymm1, ymm0
	JNE  LBB0_19                 // <--                                  // jne	.LBB0_19
	ADDQ $0x20, DI               // <--                                  // add	rdi, 32
	CMPQ DI, AX                  // <--                                  // cmp	rdi, rax
	JB   LBB0_7                  // <--                                  // jb	.LBB0_7

LBB0_9:
	CMPL   CX, $0x10         // <--                                  // cmp	ecx, 16
	JB     LBB0_12           // <--                                  // jb	.LBB0_12
	LONG   $0x076ffac5       // VMOVDQU 0(DI), X0                    // vmovdqu	xmm0, xmmword ptr [rdi]
	VPTEST LCPI0_1<>(SB), X0 // <--                                  // vptest	xmm0, xmmword ptr [rip + .LCPI0_1]
	JNE    LBB0_19           // <--                                  // jne	.LBB0_19
	ADDQ   $0x10, DI         // <--                                  // add	rdi, 16

LBB0_12:
	WORD $0xe683; BYTE $0x0f // ANDL $0xf, SI                        // and	esi, 15

LBB0_13:
	WORD $0x8548; BYTE $0xf6 // TESTQ SI, SI                         // test	rsi, rsi
	JE   LBB0_17             // <--                                  // je	.LBB0_17
	CMPQ SI, $0x8            // <--                                  // cmp	rsi, 8
	JAE  LBB0_18             // <--                                  // jae	.LBB0_18
	LONG $0x04c6f640         // TESTB $0x4, SI                       // test	sil, 4
	JNE  LBB0_20             // <--                                  // jne	.LBB0_20
	MOVQ SI, AX              // <--                                  // mov	rax, rsi
	SHRQ $0x1, AX            // <--                                  // shr	rax
	LONG $0x0704b60f         // MOVZX 0(DI)(AX*1), AX                // movzx	eax, byte ptr [rdi + rax]
	ORB  0(DI), AL           // <--                                  // or	al, byte ptr [rdi]
	ORB  -0x1(DI)(SI*1), AL  // <--                                  // or	al, byte ptr [rdi + rsi - 1]
	WORD $0x990f; BYTE $0xc0 // SETNS AL                             // setns	al
	NOP                      // (skipped)                            // mov	rsp, rbp
	NOP                      // (skipped)                            // pop	rbp
	VZEROUPPER               // <--                                  // vzeroupper
	MOVB AX, ret+16(FP)      // <--
	RET                      // <--                                  // ret

LBB0_19:
	XORL AX, AX         // <--                                  // xor	eax, eax
	NOP                 // (skipped)                            // mov	rsp, rbp
	NOP                 // (skipped)                            // pop	rbp
	VZEROUPPER          // <--                                  // vzeroupper
	MOVB AX, ret+16(FP) // <--
	RET                 // <--                                  // ret

LBB0_17:
	WORD $0x01b0        // MOVL $0x1, AL                        // mov	al, 1
	NOP                 // (skipped)                            // mov	rsp, rbp
	NOP                 // (skipped)                            // pop	rbp
	VZEROUPPER          // <--                                  // vzeroupper
	MOVB AX, ret+16(FP) // <--
	RET                 // <--                                  // ret

LBB0_18:
	MOVQ -0x8(DI)(SI*1), AX                // <--                                  // mov	rax, qword ptr [rdi + rsi - 8]
	ORQ  0(DI), AX                         // <--                                  // or	rax, qword ptr [rdi]
	QUAD $0x808080808080b948; WORD $0x8080 // MOVQ $0x8080808080808080, CX         // movabs	rcx, -9187201950435737472
	WORD $0x8548; BYTE $0xc8               // TESTQ CX, AX                         // test	rax, rcx
	WORD $0x940f; BYTE $0xc0               // SETE AL                              // sete	al
	NOP                                    // (skipped)                            // mov	rsp, rbp
	NOP                                    // (skipped)                            // pop	rbp
	VZEROUPPER                             // <--                                  // vzeroupper
	MOVB AX, ret+16(FP)                    // <--
	RET                                    // <--                                  // ret

LBB0_20:
	LONG $0xfc37448b             // MOVL -0x4(DI)(SI*1), AX              // mov	eax, dword ptr [rdi + rsi - 4]
	WORD $0x070b                 // ORL 0(DI), AX                        // or	eax, dword ptr [rdi]
	LONG $0x808080a9; BYTE $0x80 // TESTL $-0x7f7f7f80, AX               // test	eax, -2139062144
	WORD $0x940f; BYTE $0xc0     // SETE AL                              // sete	al
	NOP                          // (skipped)                            // mov	rsp, rbp
	NOP                          // (skipped)                            // pop	rbp
	VZEROUPPER                   // <--                                  // vzeroupper
	MOVB AX, ret+16(FP)          // <--
	RET                          // <--                                  // ret

DATA LCPI1_0<>+0x00(SB)/8, $0xf0f0f0f0f0f0f0f0
DATA LCPI1_0<>+0x08(SB)/8, $0xf0f0f0f0f0f0f0f0
DATA LCPI1_0<>+0x10(SB)/8, $0xf0f0f0f0f0f0f0f0
DATA LCPI1_0<>+0x18(SB)/8, $0xf0f0f0f0f0f0f0f0
GLOBL LCPI1_0<>(SB), (RODATA|NOPTR), $32

DATA LCPI1_2<>+0x00(SB)/8, $0xf8f8f8f8f8f8f8f8
DATA LCPI1_2<>+0x08(SB)/8, $0xf8f8f8f8f8f8f8f8
DATA LCPI1_2<>+0x10(SB)/8, $0xf8f8f8f8f8f8f8f8
DATA LCPI1_2<>+0x18(SB)/8, $0xf8f8f8f8f8f8f8f8
GLOBL LCPI1_2<>(SB), (RODATA|NOPTR), $32

DATA LCPI1_4<>+0x00(SB)/8, $0xfcfcfcfcfcfcfcfc
DATA LCPI1_4<>+0x08(SB)/8, $0xfcfcfcfcfcfcfcfc
DATA LCPI1_4<>+0x10(SB)/8, $0xfcfcfcfcfcfcfcfc
DATA LCPI1_4<>+0x18(SB)/8, $0xfcfcfcfcfcfcfcfc
GLOBL LCPI1_4<>(SB), (RODATA|NOPTR), $32

DATA LCPI1_6<>+0x00(SB)/8, $0x0707070707070707
DATA LCPI1_6<>+0x08(SB)/8, $0x0707070707070707
DATA LCPI1_6<>+0x10(SB)/8, $0x0707070707070707
DATA LCPI1_6<>+0x18(SB)/8, $0x0707070707070707
GLOBL LCPI1_6<>(SB), (RODATA|NOPTR), $32

DATA LCPI1_7<>+0x00(SB)/8, $0x8040201008040201
DATA LCPI1_7<>+0x08(SB)/8, $0x8040201008040201
DATA LCPI1_7<>+0x10(SB)/8, $0x8040201008040201
DATA LCPI1_7<>+0x18(SB)/8, $0x8040201008040201
GLOBL LCPI1_7<>(SB), (RODATA|NOPTR), $32

DATA LCPI1_8<>+0x00(SB)/8, $0xffffffffffffffff
DATA LCPI1_8<>+0x08(SB)/8, $0xffffffffffffffff
DATA LCPI1_8<>+0x10(SB)/8, $0xffffffffffffffff
DATA LCPI1_8<>+0x18(SB)/8, $0xffffffffffffffff
GLOBL LCPI1_8<>(SB), (RODATA|NOPTR), $32

DATA LCPI1_1<>+0x00(SB)/8, $0x0101010101010101
GLOBL LCPI1_1<>(SB), (RODATA|NOPTR), $8

DATA LCPI1_3<>+0x00(SB)/8, $0x0202020202020202
GLOBL LCPI1_3<>(SB), (RODATA|NOPTR), $8

DATA LCPI1_5<>+0x00(SB)/8, $0x0404040404040404
GLOBL LCPI1_5<>(SB), (RODATA|NOPTR), $8

DATA LCPI1_9<>+0x00(SB)/8, $0x8040201008040201
GLOBL LCPI1_9<>(SB), (RODATA|NOPTR), $8

TEXT ·indexAnyAvxBitset(SB), NOSPLIT, $0-56
	MOVQ         data+0(FP), DI
	MOVQ         data_len+8(FP), SI
	MOVQ         bitset0+16(FP), DX
	MOVQ         bitset1+24(FP), CX
	MOVQ         bitset2+32(FP), R8
	MOVQ         bitset3+40(FP), R9
	MOVQ         $-0x1, AX               // <--                                  // mov	rax, -1
	WORD         $0x8548; BYTE $0xf6     // TESTQ SI, SI                         // test	rsi, rsi
	JE           LBB1_17                 // <--                                  // je	.LBB1_17
	NOP                                  // (skipped)                            // push	rbp
	NOP                                  // (skipped)                            // mov	rbp, rsp
	NOP                                  // (skipped)                            // push	r15
	NOP                                  // (skipped)                            // push	r14
	NOP                                  // (skipped)                            // push	rbx
	NOP                                  // (skipped)                            // and	rsp, -8
	LEAQ         0(DI)(SI*1), R11        // <--                                  // lea	r11, [rdi + rsi]
	WORD         $0xe683; BYTE $0x1f     // ANDL $0x1f, SI                       // and	esi, 31
	SUBQ         SI, R11                 // <--                                  // sub	r11, rsi
	MOVQ         DI, R10                 // <--                                  // mov	r10, rdi
	CMPQ         R11, DI                 // <--                                  // cmp	r11, rdi
	JBE          LBB1_6                  // <--                                  // jbe	.LBB1_6
	LONG         $0x6ef9c1c4; BYTE $0xc1 // VMOVQ R9, X0                         // vmovq	xmm0, r9
	LONG         $0x597de2c4; BYTE $0xc0 // VPBROADCASTQ X0, Y0                  // vpbroadcastq	ymm0, xmm0
	LONG         $0x6ef9c1c4; BYTE $0xc8 // VMOVQ R8, X1                         // vmovq	xmm1, r8
	LONG         $0x597de2c4; BYTE $0xc9 // VPBROADCASTQ X1, Y1                  // vpbroadcastq	ymm1, xmm1
	LONG         $0x6ef9e1c4; BYTE $0xd1 // VMOVQ CX, X2                         // vmovq	xmm2, rcx
	LONG         $0x597de2c4; BYTE $0xd2 // VPBROADCASTQ X2, Y2                  // vpbroadcastq	ymm2, xmm2
	LONG         $0x6ef9e1c4; BYTE $0xda // VMOVQ DX, X3                         // vmovq	xmm3, rdx
	LONG         $0x597de2c4; BYTE $0xdb // VPBROADCASTQ X3, Y3                  // vpbroadcastq	ymm3, xmm3
	XORL         R10, R10                // <--                                  // xor	r10d, r10d
	LONG         $0xe4efd9c5             // VPXOR X4, X4, X4                     // vpxor	xmm4, xmm4, xmm4
	VPBROADCASTQ LCPI1_1<>(SB), Y6       // <--                                  // vpbroadcastq	ymm6, qword ptr [rip + .LCPI1_1]
	VPBROADCASTQ LCPI1_3<>(SB), Y8       // <--                                  // vpbroadcastq	ymm8, qword ptr [rip + .LCPI1_3]
	VPBROADCASTQ LCPI1_5<>(SB), Y9       // <--                                  // vpbroadcastq	ymm9, qword ptr [rip + .LCPI1_5]

LBB1_3:
	LONG         $0x6f7e21c4; WORD $0x1734 // VMOVDQU 0(DI)(R10*1), Y14            // vmovdqu	ymm14, ymmword ptr [rdi + r10]
	LONG         $0x7105c1c4; WORD $0x04f6 // VPSLLW $0x4, Y14, Y15                // vpsllw	ymm15, ymm14, 4
	VPAND        LCPI1_0<>(SB), Y15, Y15   // <--                                  // vpand	ymm15, ymm15, ymmword ptr [rip + .LCPI1_0]
	LONG         $0x645d41c4; BYTE $0xff   // VPCMPGTB Y15, Y4, Y15                // vpcmpgtb	ymm15, ymm4, ymm15
	LONG         $0xfedb05c5               // VPAND Y6, Y15, Y15                   // vpand	ymm15, ymm15, ymm6
	LONG         $0x7155c1c4; WORD $0x03f6 // VPSLLW $0x3, Y14, Y5                 // vpsllw	ymm5, ymm14, 3
	VPAND        LCPI1_2<>(SB), Y5, Y5     // <--                                  // vpand	ymm5, ymm5, ymmword ptr [rip + .LCPI1_2]
	LONG         $0xed64ddc5               // VPCMPGTB Y5, Y4, Y5                  // vpcmpgtb	ymm5, ymm4, ymm5
	LONG         $0xeddbbdc5               // VPAND Y5, Y8, Y5                     // vpand	ymm5, ymm8, ymm5
	LONG         $0xedeb85c5               // VPOR Y5, Y15, Y5                     // vpor	ymm5, ymm15, ymm5
	LONG         $0x7105c1c4; WORD $0x02f6 // VPSLLW $0x2, Y14, Y15                // vpsllw	ymm15, ymm14, 2
	VPAND        LCPI1_4<>(SB), Y15, Y15   // <--                                  // vpand	ymm15, ymm15, ymmword ptr [rip + .LCPI1_4]
	LONG         $0x645d41c4; BYTE $0xff   // VPCMPGTB Y15, Y4, Y15                // vpcmpgtb	ymm15, ymm4, ymm15
	LONG         $0xdb0541c4; BYTE $0xf9   // VPAND Y9, Y15, Y15                   // vpand	ymm15, ymm15, ymm9
	LONG         $0xedeb85c5               // VPOR Y5, Y15, Y5                     // vpor	ymm5, ymm15, ymm5
	VPAND        LCPI1_6<>(SB), Y14, Y15   // <--                                  // vpand	ymm15, ymm14, ymmword ptr [rip + .LCPI1_6]
	VPBROADCASTQ LCPI1_9<>(SB), Y7         // <--                                  // vpbroadcastq	ymm7, qword ptr [rip + .LCPI1_9]
	LONG         $0x004542c4; BYTE $0xff   // VPSHUFB Y15, Y7, Y15                 // vpshufb	ymm15, ymm7, ymm15
	LONG         $0xfc0dc1c4; BYTE $0xfe   // VPADDB Y14, Y14, Y7                  // vpaddb	ymm7, ymm14, ymm14
	LONG         $0xff64ddc5               // VPCMPGTB Y7, Y4, Y7                  // vpcmpgtb	ymm7, ymm4, ymm7
	LONG         $0x645d41c4; BYTE $0xd6   // VPCMPGTB Y14, Y4, Y10                // vpcmpgtb	ymm10, ymm4, ymm14
	LONG         $0x006562c4; BYTE $0xdd   // VPSHUFB Y5, Y3, Y11                  // vpshufb	ymm11, ymm3, ymm5
	LONG         $0x006d62c4; BYTE $0xe5   // VPSHUFB Y5, Y2, Y12                  // vpshufb	ymm12, ymm2, ymm5
	LONG         $0x007562c4; BYTE $0xed   // VPSHUFB Y5, Y1, Y13                  // vpshufb	ymm13, ymm1, ymm5
	LONG         $0x007de2c4; BYTE $0xed   // VPSHUFB Y5, Y0, Y5                   // vpshufb	ymm5, ymm0, ymm5
	LONG         $0xdb2541c4; BYTE $0xdf   // VPAND Y15, Y11, Y11                  // vpand	ymm11, ymm11, ymm15
	LONG         $0xdb1d41c4; BYTE $0xe7   // VPAND Y15, Y12, Y12                  // vpand	ymm12, ymm12, ymm15
	LONG         $0xdb1541c4; BYTE $0xef   // VPAND Y15, Y13, Y13                  // vpand	ymm13, ymm13, ymm15
	LONG         $0xeddb85c5               // VPAND Y5, Y15, Y5                    // vpand	ymm5, ymm15, ymm5
	LONG         $0xdc7425c5               // VPCMPEQB Y4, Y11, Y11                // vpcmpeqb	ymm11, ymm11, ymm4
	LONG         $0xffeb2dc5               // VPOR Y7, Y10, Y15                    // vpor	ymm15, ymm10, ymm7
	LONG         $0xeb2541c4; BYTE $0xdf   // VPOR Y15, Y11, Y11                   // vpor	ymm11, ymm11, ymm15
	LONG         $0xe4741dc5               // VPCMPEQB Y4, Y12, Y12                // vpcmpeqb	ymm12, ymm12, ymm4
	VPXOR        LCPI1_8<>(SB), Y11, Y11   // <--                                  // vpxor	ymm11, ymm11, ymmword ptr [rip + .LCPI1_8]
	LONG         $0xeb2d41c4; BYTE $0xe4   // VPOR Y12, Y10, Y12                   // vpor	ymm12, ymm10, ymm12
	LONG         $0xe7df1dc5               // VPANDN Y7, Y12, Y12                  // vpandn	ymm12, ymm12, ymm7
	LONG         $0xeb1d41c4; BYTE $0xdb   // VPOR Y11, Y12, Y11                   // vpor	ymm11, ymm12, ymm11
	LONG         $0xe47415c5               // VPCMPEQB Y4, Y13, Y12                // vpcmpeqb	ymm12, ymm13, ymm4
	LONG         $0xe7eb1dc5               // VPOR Y7, Y12, Y12                    // vpor	ymm12, ymm12, ymm7
	LONG         $0xdf1d41c4; BYTE $0xe6   // VPANDN Y14, Y12, Y12                 // vpandn	ymm12, ymm12, ymm14
	LONG         $0xec74d5c5               // VPCMPEQB Y4, Y5, Y5                  // vpcmpeqb	ymm5, ymm5, ymm4
	LONG         $0xdf55c1c4; BYTE $0xea   // VPANDN Y10, Y5, Y5                   // vpandn	ymm5, ymm5, ymm10
	LONG         $0xefdbd5c5               // VPAND Y7, Y5, Y5                     // vpand	ymm5, ymm5, ymm7
	LONG         $0xedeb9dc5               // VPOR Y5, Y12, Y5                     // vpor	ymm5, ymm12, ymm5
	LONG         $0xedeba5c5               // VPOR Y5, Y11, Y5                     // vpor	ymm5, ymm11, ymm5
	LONG         $0xddd7fdc5               // VPMOVMSKB Y5, BX                     // vpmovmskb	ebx, ymm5
	WORD         $0xdb85                   // TESTL BX, BX                         // test	ebx, ebx
	JNE          LBB1_14                   // <--                                  // jne	.LBB1_14
	LEAQ         0(DI)(R10*1), BX          // <--                                  // lea	rbx, [rdi + r10]
	ADDQ         $0x20, BX                 // <--                                  // add	rbx, 32
	ADDQ         $0x20, R10                // <--                                  // add	r10, 32
	CMPQ         BX, R11                   // <--                                  // cmp	rbx, r11
	JB           LBB1_3                    // <--                                  // jb	.LBB1_3
	ADDQ         DI, R10                   // <--                                  // add	r10, rdi

LBB1_6:
	WORD $0x8548; BYTE $0xf6 // TESTQ SI, SI                         // test	rsi, rsi
	JE   LBB1_16             // <--                                  // je	.LBB1_16
	XORL R11, R11            // <--                                  // xor	r11d, r11d

LBB1_8:
	LONG $0x1cb60f43; BYTE $0x1a // MOVZX 0(R10)(R11*1), BX              // movzx	ebx, byte ptr [r10 + r11]
	WORD $0x8941; BYTE $0xdf     // MOVL BX, R15                         // mov	r15d, ebx
	LONG $0x06efc141             // SHRL $0x6, R15                       // shr	r15d, 6
	MOVQ DX, R14                 // <--                                  // mov	r14, rdx
	JE   LBB1_12                 // <--                                  // je	.LBB1_12
	MOVQ R8, R14                 // <--                                  // mov	r14, r8
	CMPL R15, $0x2               // <--                                  // cmp	r15d, 2
	JE   LBB1_12                 // <--                                  // je	.LBB1_12
	MOVQ CX, R14                 // <--                                  // mov	r14, rcx
	CMPL R15, $0x1               // <--                                  // cmp	r15d, 1
	JE   LBB1_12                 // <--                                  // je	.LBB1_12
	MOVQ R9, R14                 // <--                                  // mov	r14, r9

LBB1_12:
	BTQ  BX, R14 // <--                                  // bt	r14, rbx
	JB   LBB1_15 // <--                                  // jb	.LBB1_15
	INCQ R11     // <--                                  // inc	r11
	CMPQ SI, R11 // <--                                  // cmp	rsi, r11
	JNE  LBB1_8  // <--                                  // jne	.LBB1_8
	JMP  LBB1_16 // <--                                  // jmp	.LBB1_16

LBB1_14:
	LONG $0xc3bc0ff3 // TZCNT BX, AX                         // rep		bsf	eax, ebx
	ADDQ R10, AX     // <--                                  // add	rax, r10
	JMP  LBB1_16     // <--                                  // jmp	.LBB1_16

LBB1_15:
	SUBQ DI, R10  // <--                                  // sub	r10, rdi
	ADDQ R11, R10 // <--                                  // add	r10, r11
	MOVQ R10, AX  // <--                                  // mov	rax, r10

LBB1_16:
	NOP // (skipped)                            // lea	rsp, [rbp - 24]
	NOP // (skipped)                            // pop	rbx
	NOP // (skipped)                            // pop	r14
	NOP // (skipped)                            // pop	r15
	NOP // (skipped)                            // pop	rbp

LBB1_17:
	VZEROUPPER          // <--                                  // vzeroupper
	MOVQ AX, ret+48(FP) // <--
	RET                 // <--                                  // ret

DATA LCPI2_0<>+0x00(SB)/8, $0x2020202020202020
DATA LCPI2_0<>+0x08(SB)/8, $0x2020202020202020
DATA LCPI2_0<>+0x10(SB)/8, $0x2020202020202020
DATA LCPI2_0<>+0x18(SB)/8, $0x2020202020202020
GLOBL LCPI2_0<>(SB), (RODATA|NOPTR), $32

DATA LCPI2_1<>+0x00(SB)/8, $0x1f1f1f1f1f1f1f1f
DATA LCPI2_1<>+0x08(SB)/8, $0x1f1f1f1f1f1f1f1f
DATA LCPI2_1<>+0x10(SB)/8, $0x1f1f1f1f1f1f1f1f
DATA LCPI2_1<>+0x18(SB)/8, $0x1f1f1f1f1f1f1f1f
GLOBL LCPI2_1<>(SB), (RODATA|NOPTR), $32

DATA LCPI2_2<>+0x00(SB)/8, $0x9a9a9a9a9a9a9a9a
DATA LCPI2_2<>+0x08(SB)/8, $0x9a9a9a9a9a9a9a9a
DATA LCPI2_2<>+0x10(SB)/8, $0x9a9a9a9a9a9a9a9a
DATA LCPI2_2<>+0x18(SB)/8, $0x9a9a9a9a9a9a9a9a
GLOBL LCPI2_2<>(SB), (RODATA|NOPTR), $32

DATA LCPI2_3<>+0x00(SB)/8, $0x7f7f7f7f7f7f7f7f
DATA LCPI2_3<>+0x08(SB)/8, $0x7f7f7f7f7f7f7f7f
GLOBL LCPI2_3<>(SB), (RODATA|NOPTR), $16

DATA LCPI2_4<>+0x00(SB)/8, $0xfafafafafafafafa
DATA LCPI2_4<>+0x08(SB)/8, $0xfafafafafafafafa
GLOBL LCPI2_4<>(SB), (RODATA|NOPTR), $16

DATA LCPI2_5<>+0x00(SB)/8, $0x1f1f1f1f1f1f1f1f
DATA LCPI2_5<>+0x08(SB)/8, $0x1f1f1f1f1f1f1f1f
GLOBL LCPI2_5<>(SB), (RODATA|NOPTR), $16

DATA LCPI2_6<>+0x00(SB)/8, $0x2020202020202020
DATA LCPI2_6<>+0x08(SB)/8, $0x2020202020202020
GLOBL LCPI2_6<>(SB), (RODATA|NOPTR), $16

DATA LCPI2_7<>+0x00(SB)/1, $0x20
GLOBL LCPI2_7<>(SB), (RODATA|NOPTR), $1

DATA LCPI2_8<>+0x00(SB)/1, $0x1f
GLOBL LCPI2_8<>(SB), (RODATA|NOPTR), $1

DATA LCPI2_9<>+0x00(SB)/1, $0x9a
GLOBL LCPI2_9<>(SB), (RODATA|NOPTR), $1

DATA LCPI2_10<>+0x00(SB)/1, $0x7f
GLOBL LCPI2_10<>(SB), (RODATA|NOPTR), $1

DATA LCPI2_11<>+0x00(SB)/1, $0xfa
GLOBL LCPI2_11<>(SB), (RODATA|NOPTR), $1

TEXT ·equalFoldAvx(SB), NOSPLIT, $0-33
	MOVQ a+0(FP), DI
	MOVQ a_len+8(FP), SI
	MOVQ b+16(FP), DX
	MOVQ b_len+24(FP), CX
	CMPQ SI, CX           // <--                                  // cmp	rsi, rcx
	JNE  LBB2_9           // <--                                  // jne	.LBB2_9
	NOP                   // (skipped)                            // push	rbp
	NOP                   // (skipped)                            // mov	rbp, rsp
	NOP                   // (skipped)                            // and	rsp, -8
	CMPQ SI, $0x1f        // <--                                  // cmp	rsi, 31
	JA   LBB2_10          // <--                                  // ja	.LBB2_10
	CMPQ SI, $0x8         // <--                                  // cmp	rsi, 8
	JAE  LBB2_20          // <--                                  // jae	.LBB2_20
	XORL CX, CX           // <--                                  // xor	ecx, ecx

LBB2_4:
	WORD $0x01b0 // MOVL $0x1, AL                        // mov	al, 1
	CMPQ CX, SI  // <--                                  // cmp	rcx, rsi
	JAE  LBB2_8  // <--                                  // jae	.LBB2_8
	DECQ SI      // <--                                  // dec	rsi

LBB2_6:
	LONG $0x0f04b60f             // MOVZX 0(DI)(CX*1), AX                // movzx	eax, byte ptr [rdi + rcx]
	LONG $0x14b60f44; BYTE $0x0a // MOVZX 0(DX)(CX*1), R10               // movzx	r10d, byte ptr [rdx + rcx]
	LONG $0x9f408d44             // LEAL -0x61(AX), R8                   // lea	r8d, [rax - 97]
	LONG $0xe0488d44             // LEAL -0x20(AX), R9                   // lea	r9d, [rax - 32]
	CMPB R8, $0x1a               // <--                                  // cmp	r8b, 26
	LONG $0xc1b60f45             // MOVZX R9, R8                         // movzx	r8d, r9b
	LONG $0xc0430f44             // CMOVAE AX, R8                        // cmovae	r8d, eax
	LONG $0x9f428d41             // LEAL -0x61(R10), AX                  // lea	eax, [r10 - 97]
	LONG $0xe04a8d45             // LEAL -0x20(R10), R9                  // lea	r9d, [r10 - 32]
	WORD $0x1a3c                 // CMPL AL, $0x1a                       // cmp	al, 26
	LONG $0xc9b60f45             // MOVZX R9, R9                         // movzx	r9d, r9b
	LONG $0xca430f45             // CMOVAE R10, R9                       // cmovae	r9d, r10d
	CMPB R8, R9                  // <--                                  // cmp	r8b, r9b
	WORD $0x940f; BYTE $0xc0     // SETE AL                              // sete	al
	CMPQ SI, CX                  // <--                                  // cmp	rsi, rcx
	JE   LBB2_8                  // <--                                  // je	.LBB2_8
	INCQ CX                      // <--                                  // inc	rcx
	CMPB R8, R9                  // <--                                  // cmp	r8b, r9b
	JE   LBB2_6                  // <--                                  // je	.LBB2_6

LBB2_8:
	NOP                 // (skipped)                            // mov	rsp, rbp
	NOP                 // (skipped)                            // pop	rbp
	MOVB AX, ret+32(FP) // <--
	RET                 // <--                                  // ret

LBB2_9:
	XORL AX, AX         // <--                                  // xor	eax, eax
	MOVB AX, ret+32(FP) // <--
	RET                 // <--                                  // ret

LBB2_10:
	LEAQ         0(DI)(SI*1), CX     // <--                                  // lea	rcx, [rdi + rsi]
	WORD         $0xf089             // MOVL SI, AX                          // mov	eax, esi
	WORD         $0xe083; BYTE $0x3f // ANDL $0x3f, AX                       // and	eax, 63
	SUBQ         AX, CX              // <--                                  // sub	rcx, rax
	CMPQ         CX, DI              // <--                                  // cmp	rcx, rdi
	JBE          LBB2_14             // <--                                  // jbe	.LBB2_14
	VPBROADCASTB LCPI2_7<>(SB), Y0   // <--                                  // vpbroadcastb	ymm0, byte ptr [rip + .LCPI2_7]
	VPBROADCASTB LCPI2_8<>(SB), Y1   // <--                                  // vpbroadcastb	ymm1, byte ptr [rip + .LCPI2_8]
	VPBROADCASTB LCPI2_9<>(SB), Y2   // <--                                  // vpbroadcastb	ymm2, byte ptr [rip + .LCPI2_9]
	LONG         $0xdb76e5c5         // VPCMPEQD Y3, Y3, Y3                  // vpcmpeqd	ymm3, ymm3, ymm3

LBB2_12:
	LONG $0x276ffec5             // VMOVDQU 0(DI), Y4                    // vmovdqu	ymm4, ymmword ptr [rdi]
	LONG $0x6f6ffec5; BYTE $0x20 // VMOVDQU 0x20(DI), Y5                 // vmovdqu	ymm5, ymmword ptr [rdi + 32]
	LONG $0x32efddc5             // VPXOR 0(DX), Y4, Y6                  // vpxor	ymm6, ymm4, ymmword ptr [rdx]
	LONG $0xf874cdc5             // VPCMPEQB Y0, Y6, Y7                  // vpcmpeqb	ymm7, ymm6, ymm0
	LONG $0xe0ebddc5             // VPOR Y0, Y4, Y4                      // vpor	ymm4, ymm4, ymm0
	LONG $0xe1fcddc5             // VPADDB Y1, Y4, Y4                    // vpaddb	ymm4, ymm4, ymm1
	LONG $0xe464edc5             // VPCMPGTB Y4, Y2, Y4                  // vpcmpgtb	ymm4, ymm2, ymm4
	LONG $0xe4dbc5c5             // VPAND Y4, Y7, Y4                     // vpand	ymm4, ymm7, ymm4
	LONG $0xf471ddc5; BYTE $0x05 // VPSLLW $0x5, Y4, Y4                  // vpsllw	ymm4, ymm4, 5
	LONG $0xe0dbddc5             // VPAND Y0, Y4, Y4                     // vpand	ymm4, ymm4, ymm0
	LONG $0x7aefd5c5; BYTE $0x20 // VPXOR 0x20(DX), Y5, Y7               // vpxor	ymm7, ymm5, ymmword ptr [rdx + 32]
	LONG $0xe674ddc5             // VPCMPEQB Y6, Y4, Y4                  // vpcmpeqb	ymm4, ymm4, ymm6
	LONG $0xf074c5c5             // VPCMPEQB Y0, Y7, Y6                  // vpcmpeqb	ymm6, ymm7, ymm0
	LONG $0xe8ebd5c5             // VPOR Y0, Y5, Y5                      // vpor	ymm5, ymm5, ymm0
	LONG $0xe9fcd5c5             // VPADDB Y1, Y5, Y5                    // vpaddb	ymm5, ymm5, ymm1
	LONG $0xed64edc5             // VPCMPGTB Y5, Y2, Y5                  // vpcmpgtb	ymm5, ymm2, ymm5
	LONG $0xeddbcdc5             // VPAND Y5, Y6, Y5                     // vpand	ymm5, ymm6, ymm5
	LONG $0xf571d5c5; BYTE $0x05 // VPSLLW $0x5, Y5, Y5                  // vpsllw	ymm5, ymm5, 5
	LONG $0xe8dbd5c5             // VPAND Y0, Y5, Y5                     // vpand	ymm5, ymm5, ymm0
	LONG $0xef74d5c5             // VPCMPEQB Y7, Y5, Y5                  // vpcmpeqb	ymm5, ymm5, ymm7
	LONG $0xe4dbd5c5             // VPAND Y4, Y5, Y4                     // vpand	ymm4, ymm5, ymm4
	LONG $0x177de2c4; BYTE $0xe3 // VPTEST Y3, Y4                        // vptest	ymm4, ymm3
	JAE  LBB2_24                 // <--                                  // jae	.LBB2_24
	ADDQ $0x40, DI               // <--                                  // add	rdi, 64
	ADDQ $0x40, DX               // <--                                  // add	rdx, 64
	CMPQ DI, CX                  // <--                                  // cmp	rdi, rcx
	JB   LBB2_12                 // <--                                  // jb	.LBB2_12

LBB2_14:
	ADDQ         DI, AX              // <--                                  // add	rax, rdi
	WORD         $0xe683; BYTE $0x1f // ANDL $0x1f, SI                       // and	esi, 31
	SUBQ         SI, AX              // <--                                  // sub	rax, rsi
	CMPQ         DI, AX              // <--                                  // cmp	rdi, rax
	JAE          LBB2_18             // <--                                  // jae	.LBB2_18
	VPBROADCASTB LCPI2_7<>(SB), Y0   // <--                                  // vpbroadcastb	ymm0, byte ptr [rip + .LCPI2_7]
	VPBROADCASTB LCPI2_8<>(SB), Y1   // <--                                  // vpbroadcastb	ymm1, byte ptr [rip + .LCPI2_8]
	VPBROADCASTB LCPI2_9<>(SB), Y2   // <--                                  // vpbroadcastb	ymm2, byte ptr [rip + .LCPI2_9]
	LONG         $0xdb76e5c5         // VPCMPEQD Y3, Y3, Y3                  // vpcmpeqd	ymm3, ymm3, ymm3

LBB2_16:
	LONG $0x276ffec5             // VMOVDQU 0(DI), Y4                    // vmovdqu	ymm4, ymmword ptr [rdi]
	LONG $0x2aefddc5             // VPXOR 0(DX), Y4, Y5                  // vpxor	ymm5, ymm4, ymmword ptr [rdx]
	LONG $0xf074d5c5             // VPCMPEQB Y0, Y5, Y6                  // vpcmpeqb	ymm6, ymm5, ymm0
	LONG $0xe0ebddc5             // VPOR Y0, Y4, Y4                      // vpor	ymm4, ymm4, ymm0
	LONG $0xe1fcddc5             // VPADDB Y1, Y4, Y4                    // vpaddb	ymm4, ymm4, ymm1
	LONG $0xe464edc5             // VPCMPGTB Y4, Y2, Y4                  // vpcmpgtb	ymm4, ymm2, ymm4
	LONG $0xe6dbddc5             // VPAND Y6, Y4, Y4                     // vpand	ymm4, ymm4, ymm6
	LONG $0xf471ddc5; BYTE $0x05 // VPSLLW $0x5, Y4, Y4                  // vpsllw	ymm4, ymm4, 5
	LONG $0xe0dbddc5             // VPAND Y0, Y4, Y4                     // vpand	ymm4, ymm4, ymm0
	LONG $0xe574ddc5             // VPCMPEQB Y5, Y4, Y4                  // vpcmpeqb	ymm4, ymm4, ymm5
	LONG $0x177de2c4; BYTE $0xe3 // VPTEST Y3, Y4                        // vptest	ymm4, ymm3
	JAE  LBB2_24                 // <--                                  // jae	.LBB2_24
	ADDQ $0x20, DI               // <--                                  // add	rdi, 32
	ADDQ $0x20, DX               // <--                                  // add	rdx, 32
	CMPQ DI, AX                  // <--                                  // cmp	rdi, rax
	JB   LBB2_16                 // <--                                  // jb	.LBB2_16

LBB2_18:
	WORD         $0x8548; BYTE $0xf6       // TESTQ SI, SI                         // test	rsi, rsi
	JE           LBB2_26                   // <--                                  // je	.LBB2_26
	LONG         $0x446ffec5; WORD $0xe037 // VMOVDQU -0x20(DI)(SI*1), Y0          // vmovdqu	ymm0, ymmword ptr [rdi + rsi - 32]
	LONG         $0x4ceffdc5; WORD $0xe032 // VPXOR -0x20(DX)(SI*1), Y0, Y1        // vpxor	ymm1, ymm0, ymmword ptr [rdx + rsi - 32]
	VPBROADCASTB LCPI2_7<>(SB), Y2         // <--                                  // vpbroadcastb	ymm2, byte ptr [rip + .LCPI2_7]
	LONG         $0xda74f5c5               // VPCMPEQB Y2, Y1, Y3                  // vpcmpeqb	ymm3, ymm1, ymm2
	LONG         $0xc2ebfdc5               // VPOR Y2, Y0, Y0                      // vpor	ymm0, ymm0, ymm2
	VPADDB       LCPI2_1<>(SB), Y0, Y0     // <--                                  // vpaddb	ymm0, ymm0, ymmword ptr [rip + .LCPI2_1]
	VPBROADCASTB LCPI2_9<>(SB), Y4         // <--                                  // vpbroadcastb	ymm4, byte ptr [rip + .LCPI2_9]
	LONG         $0xc064ddc5               // VPCMPGTB Y0, Y4, Y0                  // vpcmpgtb	ymm0, ymm4, ymm0
	LONG         $0xc3dbfdc5               // VPAND Y3, Y0, Y0                     // vpand	ymm0, ymm0, ymm3
	LONG         $0xf071fdc5; BYTE $0x05   // VPSLLW $0x5, Y0, Y0                  // vpsllw	ymm0, ymm0, 5
	LONG         $0xc2dbfdc5               // VPAND Y2, Y0, Y0                     // vpand	ymm0, ymm0, ymm2
	LONG         $0xc174fdc5               // VPCMPEQB Y1, Y0, Y0                  // vpcmpeqb	ymm0, ymm0, ymm1
	LONG         $0xc976f5c5               // VPCMPEQD Y1, Y1, Y1                  // vpcmpeqd	ymm1, ymm1, ymm1
	LONG         $0x177de2c4; BYTE $0xc1   // VPTEST Y1, Y0                        // vptest	ymm0, ymm1
	WORD         $0x920f; BYTE $0xc0       // SETB AL                              // setb	al
	NOP                                    // (skipped)                            // mov	rsp, rbp
	NOP                                    // (skipped)                            // pop	rbp
	VZEROUPPER                             // <--                                  // vzeroupper
	MOVB         AX, ret+32(FP)            // <--
	RET                                    // <--                                  // ret

LBB2_20:
	XORL         AX, AX             // <--                                  // xor	eax, eax
	VPBROADCASTB LCPI2_10<>(SB), X0 // <--                                  // vpbroadcastb	xmm0, byte ptr [rip + .LCPI2_10]
	VPBROADCASTB LCPI2_11<>(SB), X1 // <--                                  // vpbroadcastb	xmm1, byte ptr [rip + .LCPI2_11]
	VPBROADCASTB LCPI2_8<>(SB), X2  // <--                                  // vpbroadcastb	xmm2, byte ptr [rip + .LCPI2_8]
	VPBROADCASTB LCPI2_7<>(SB), X3  // <--                                  // vpbroadcastb	xmm3, byte ptr [rip + .LCPI2_7]
	JMP          LBB2_22            // <--                                  // jmp	.LBB2_22

LBB2_21:
	LEAQ 0x8(AX), CX // <--                                  // lea	rcx, [rax + 8]
	ADDQ $0x10, AX   // <--                                  // add	rax, 16
	CMPQ AX, SI      // <--                                  // cmp	rax, rsi
	MOVQ CX, AX      // <--                                  // mov	rax, rcx
	JA   LBB2_4      // <--                                  // ja	.LBB2_4

LBB2_22:
	MOVQ 0(DI)(AX*1), CX         // <--                                  // mov	rcx, qword ptr [rdi + rax]
	MOVQ 0(DX)(AX*1), R8         // <--                                  // mov	r8, qword ptr [rdx + rax]
	CMPQ CX, R8                  // <--                                  // cmp	rcx, r8
	JE   LBB2_21                 // <--                                  // je	.LBB2_21
	LONG $0x6ef9c1c4; BYTE $0xe0 // VMOVQ R8, X4                         // vmovq	xmm4, r8
	LONG $0x6ef9e1c4; BYTE $0xe9 // VMOVQ CX, X5                         // vmovq	xmm5, rcx
	LONG $0xe46cd1c5             // VPUNPCKLQDQ X4, X5, X4               // vpunpcklqdq	xmm4, xmm5, xmm4
	LONG $0xe8dbd9c5             // VPAND X0, X4, X5                     // vpand	xmm5, xmm4, xmm0
	LONG $0xf5fbf1c5             // VPSUBQ X5, X1, X6                    // vpsubq	xmm6, xmm1, xmm5
	LONG $0xf6dfd9c5             // VPANDN X6, X4, X6                    // vpandn	xmm6, xmm4, xmm6
	LONG $0xead4d1c5             // VPADDQ X2, X5, X5                    // vpaddq	xmm5, xmm5, xmm2
	LONG $0xeddbc9c5             // VPAND X5, X6, X5                     // vpand	xmm5, xmm6, xmm5
	LONG $0xd573d1c5; BYTE $0x02 // VPSRLQ $0x2, X5, X5                  // vpsrlq	xmm5, xmm5, 2
	LONG $0xebdbd1c5             // VPAND X3, X5, X5                     // vpand	xmm5, xmm5, xmm3
	LONG $0xe5fbd9c5             // VPSUBQ X5, X4, X4                    // vpsubq	xmm4, xmm4, xmm5
	LONG $0xec70f9c5; BYTE $0xee // VPSHUFD $-0x12, X4, X5               // vpshufd	xmm5, xmm4, 238
	LONG $0x2959e2c4; BYTE $0xe5 // VPCMPEQQ X5, X4, X4                  // vpcmpeqq	xmm4, xmm4, xmm5
	LONG $0xe17ef9c5             // VMOVD X4, CX                         // vmovd	ecx, xmm4
	WORD $0xc1f6; BYTE $0x01     // TESTL $0x1, CL                       // test	cl, 1
	JNE  LBB2_21                 // <--                                  // jne	.LBB2_21

LBB2_24:
	XORL AX, AX         // <--                                  // xor	eax, eax
	NOP                 // (skipped)                            // mov	rsp, rbp
	NOP                 // (skipped)                            // pop	rbp
	VZEROUPPER          // <--                                  // vzeroupper
	MOVB AX, ret+32(FP) // <--
	RET                 // <--                                  // ret

LBB2_26:
	WORD $0x01b0        // MOVL $0x1, AL                        // mov	al, 1
	NOP                 // (skipped)                            // mov	rsp, rbp
	NOP                 // (skipped)                            // pop	rbp
	VZEROUPPER          // <--                                  // vzeroupper
	MOVB AX, ret+32(FP) // <--
	RET                 // <--                                  // ret

TEXT ·indexMaskAvx(SB), NOSPLIT, $0-32
	MOVQ    data+0(FP), DI
	MOVQ    length+8(FP), SI
	MOVBQZX mask+16(FP), DX
	NOP                             // (skipped)                            // push	rbp
	NOP                             // (skipped)                            // mov	rbp, rsp
	NOP                             // (skipped)                            // and	rsp, -8
	CMPQ    SI, $0x10               // <--                                  // cmp	rsi, 16
	JB      LBB3_19                 // <--                                  // jb	.LBB3_19
	LONG    $0xc26ef9c5             // VMOVD DX, X0                         // vmovd	xmm0, edx
	LONG    $0x787de2c4; BYTE $0xc0 // VPBROADCASTB X0, Y0                  // vpbroadcastb	ymm0, xmm0
	LEAQ    0(DI)(SI*1), R8         // <--                                  // lea	r8, [rdi + rsi]
	WORD    $0xf089                 // MOVL SI, AX                          // mov	eax, esi
	WORD    $0xe083; BYTE $0x7f     // ANDL $0x7f, AX                       // and	eax, 127
	SUBQ    AX, R8                  // <--                                  // sub	r8, rax
	MOVQ    DI, CX                  // <--                                  // mov	rcx, rdi
	CMPQ    R8, DI                  // <--                                  // cmp	r8, rdi
	JBE     LBB3_6                  // <--                                  // jbe	.LBB3_6
	XORL    CX, CX                  // <--                                  // xor	ecx, ecx

LBB3_3:
	LONG $0x246ffec5; BYTE $0x0f   // VMOVDQU 0(DI)(CX*1), Y4              // vmovdqu	ymm4, ymmword ptr [rdi + rcx]
	LONG $0x5c6ffec5; WORD $0x200f // VMOVDQU 0x20(DI)(CX*1), Y3           // vmovdqu	ymm3, ymmword ptr [rdi + rcx + 32]
	LONG $0x546ffec5; WORD $0x400f // VMOVDQU 0x40(DI)(CX*1), Y2           // vmovdqu	ymm2, ymmword ptr [rdi + rcx + 64]
	LONG $0x4c6ffec5; WORD $0x600f // VMOVDQU 0x60(DI)(CX*1), Y1           // vmovdqu	ymm1, ymmword ptr [rdi + rcx + 96]
	LONG $0xecebe5c5               // VPOR Y4, Y3, Y5                      // vpor	ymm5, ymm3, ymm4
	LONG $0xf1ebedc5               // VPOR Y1, Y2, Y6                      // vpor	ymm6, ymm2, ymm1
	LONG $0xeeebd5c5               // VPOR Y6, Y5, Y5                      // vpor	ymm5, ymm5, ymm6
	LONG $0x177de2c4; BYTE $0xe8   // VPTEST Y0, Y5                        // vptest	ymm5, ymm0
	JNE  LBB3_29                   // <--                                  // jne	.LBB3_29
	LEAQ 0(DI)(CX*1), R9           // <--                                  // lea	r9, [rdi + rcx]
	SUBQ $-0x80, CX                // <--                                  // sub	rcx, -128
	SUBQ $-0x80, R9                // <--                                  // sub	r9, -128
	CMPQ R9, R8                    // <--                                  // cmp	r9, r8
	JB   LBB3_3                    // <--                                  // jb	.LBB3_3
	ADDQ DI, CX                    // <--                                  // add	rcx, rdi

LBB3_6:
	ADDQ CX, AX              // <--                                  // add	rax, rcx
	WORD $0xe683; BYTE $0x1f // ANDL $0x1f, SI                       // and	esi, 31
	SUBQ SI, AX              // <--                                  // sub	rax, rsi
	CMPQ CX, AX              // <--                                  // cmp	rcx, rax
	JAE  LBB3_10             // <--                                  // jae	.LBB3_10
	MOVQ CX, R8              // <--                                  // mov	r8, rcx
	SUBQ DI, R8              // <--                                  // sub	r8, rdi

LBB3_8:
	LONG $0x096ffec5             // VMOVDQU 0(CX), Y1                    // vmovdqu	ymm1, ymmword ptr [rcx]
	LONG $0x177de2c4; BYTE $0xc8 // VPTEST Y0, Y1                        // vptest	ymm1, ymm0
	JNE  LBB3_32                 // <--                                  // jne	.LBB3_32
	ADDQ $0x20, CX               // <--                                  // add	rcx, 32
	ADDQ $0x20, R8               // <--                                  // add	r8, 32
	CMPQ CX, AX                  // <--                                  // cmp	rcx, rax
	JB   LBB3_8                  // <--                                  // jb	.LBB3_8

LBB3_10:
	CMPL SI, $0x10               // <--                                  // cmp	esi, 16
	JB   LBB3_13                 // <--                                  // jb	.LBB3_13
	LONG $0x096ffac5             // VMOVDQU 0(CX), X1                    // vmovdqu	xmm1, xmmword ptr [rcx]
	LONG $0x1779e2c4; BYTE $0xc8 // VPTEST X0, X1                        // vptest	xmm1, xmm0
	JNE  LBB3_35                 // <--                                  // jne	.LBB3_35
	ADDQ $0x10, CX               // <--                                  // add	rcx, 16
	ADDQ $-0x10, SI              // <--                                  // add	rsi, -16

LBB3_13:
	WORD $0xb60f; BYTE $0xc2       // MOVZX DL, AX                         // movzx	eax, dl
	LONG $0x0101c069; WORD $0x0101 // IMULL $0x1010101, AX, AX             // imul	eax, eax, 16843009
	CMPQ SI, $0x8                  // <--                                  // cmp	rsi, 8
	JB   LBB3_14                   // <--                                  // jb	.LBB3_14

LBB3_20:
	WORD $0x8941; BYTE $0xc0     // MOVL AX, R8                          // mov	r8d, eax
	MOVQ R8, DX                  // <--                                  // mov	rdx, r8
	SHLQ $0x20, DX               // <--                                  // shl	rdx, 32
	ORQ  R8, DX                  // <--                                  // or	rdx, r8
	ANDQ 0(CX), DX               // <--                                  // and	rdx, qword ptr [rcx]
	JE   LBB3_22                 // <--                                  // je	.LBB3_22
	SUBQ DI, CX                  // <--                                  // sub	rcx, rdi
	LONG $0xbc0f48f3; BYTE $0xc2 // TZCNT DX, AX                         // rep		bsf	rax, rdx
	JMP  LBB3_28                 // <--                                  // jmp	.LBB3_28

LBB3_19:
	MOVQ DI, CX                    // <--                                  // mov	rcx, rdi
	WORD $0xb60f; BYTE $0xc2       // MOVZX DL, AX                         // movzx	eax, dl
	LONG $0x0101c069; WORD $0x0101 // IMULL $0x1010101, AX, AX             // imul	eax, eax, 16843009
	CMPQ SI, $0x8                  // <--                                  // cmp	rsi, 8
	JAE  LBB3_20                   // <--                                  // jae	.LBB3_20

LBB3_14:
	CMPQ SI, $0x4 // <--                                  // cmp	rsi, 4
	JB   LBB3_15  // <--                                  // jb	.LBB3_15

LBB3_23:
	WORD $0x118b   // MOVL 0(CX), DX                       // mov	edx, dword ptr [rcx]
	WORD $0xc221   // ANDL AX, DX                          // and	edx, eax
	JNE  LBB3_27   // <--                                  // jne	.LBB3_27
	ADDQ $0x4, CX  // <--                                  // add	rcx, 4
	ADDQ $-0x4, SI // <--                                  // add	rsi, -4
	CMPQ SI, $0x1  // <--                                  // cmp	rsi, 1
	JNE  LBB3_16   // <--                                  // jne	.LBB3_16

LBB3_25:
	WORD $0xb60f; BYTE $0x11 // MOVZX 0(CX), DX                      // movzx	edx, byte ptr [rcx]
	JMP  LBB3_26             // <--                                  // jmp	.LBB3_26

LBB3_22:
	ADDQ $0x8, CX  // <--                                  // add	rcx, 8
	ADDQ $-0x8, SI // <--                                  // add	rsi, -8
	CMPQ SI, $0x4  // <--                                  // cmp	rsi, 4
	JAE  LBB3_23   // <--                                  // jae	.LBB3_23

LBB3_15:
	CMPQ SI, $0x1 // <--                                  // cmp	rsi, 1
	JE   LBB3_25  // <--                                  // je	.LBB3_25

LBB3_16:
	CMPQ SI, $0x2            // <--                                  // cmp	rsi, 2
	JE   LBB3_33             // <--                                  // je	.LBB3_33
	XORL DX, DX              // <--                                  // xor	edx, edx
	CMPQ SI, $0x3            // <--                                  // cmp	rsi, 3
	JNE  LBB3_26             // <--                                  // jne	.LBB3_26
	WORD $0xb70f; BYTE $0x31 // MOVZX 0(CX), SI                      // movzx	esi, word ptr [rcx]
	LONG $0x0251b60f         // MOVZX 0x2(CX), DX                    // movzx	edx, byte ptr [rcx + 2]
	WORD $0xe2c1; BYTE $0x10 // SHLL $0x10, DX                       // shl	edx, 16
	WORD $0xf209             // ORL SI, DX                           // or	edx, esi
	WORD $0xc221             // ANDL AX, DX                          // and	edx, eax
	JNE  LBB3_27             // <--                                  // jne	.LBB3_27
	JMP  LBB3_34             // <--                                  // jmp	.LBB3_34

LBB3_26:
	WORD $0xc221 // ANDL AX, DX                          // and	edx, eax
	JE   LBB3_34 // <--                                  // je	.LBB3_34

LBB3_27:
	SUBQ DI, CX      // <--                                  // sub	rcx, rdi
	LONG $0xc2bc0ff3 // TZCNT DX, AX                         // rep		bsf	eax, edx

LBB3_28:
	WORD $0xe8c1; BYTE $0x03 // SHRL $0x3, AX                        // shr	eax, 3
	ADDQ CX, AX              // <--                                  // add	rax, rcx
	NOP                      // (skipped)                            // mov	rsp, rbp
	NOP                      // (skipped)                            // pop	rbp
	VZEROUPPER               // <--                                  // vzeroupper
	MOVQ AX, ret+24(FP)      // <--
	RET                      // <--                                  // ret

LBB3_29:
	LONG $0xe8dbddc5 // VPAND Y0, Y4, Y5                     // vpand	ymm5, ymm4, ymm0
	LONG $0xe4efd9c5 // VPXOR X4, X4, X4                     // vpxor	xmm4, xmm4, xmm4
	LONG $0xec74d5c5 // VPCMPEQB Y4, Y5, Y5                  // vpcmpeqb	ymm5, ymm5, ymm4
	LONG $0xc5d7fdc5 // VPMOVMSKB Y5, AX                     // vpmovmskb	eax, ymm5
	CMPL AX, $-0x1   // <--                                  // cmp	eax, -1
	JE   LBB3_36     // <--                                  // je	.LBB3_36
	WORD $0xd0f7     // NOTL AX                              // not	eax
	JMP  LBB3_31     // <--                                  // jmp	.LBB3_31

LBB3_32:
	LONG $0xc0dbf5c5    // VPAND Y0, Y1, Y0                     // vpand	ymm0, ymm1, ymm0
	LONG $0xc9eff1c5    // VPXOR X1, X1, X1                     // vpxor	xmm1, xmm1, xmm1
	LONG $0xc174fdc5    // VPCMPEQB Y1, Y0, Y0                  // vpcmpeqb	ymm0, ymm0, ymm1
	LONG $0xc0d7fdc5    // VPMOVMSKB Y0, AX                     // vpmovmskb	eax, ymm0
	WORD $0xd0f7        // NOTL AX                              // not	eax
	LONG $0xc0bc0ff3    // TZCNT AX, AX                         // rep		bsf	eax, eax
	ADDQ R8, AX         // <--                                  // add	rax, r8
	NOP                 // (skipped)                            // mov	rsp, rbp
	NOP                 // (skipped)                            // pop	rbp
	VZEROUPPER          // <--                                  // vzeroupper
	MOVQ AX, ret+24(FP) // <--
	RET                 // <--                                  // ret

LBB3_33:
	WORD $0xb70f; BYTE $0x11 // MOVZX 0(CX), DX                      // movzx	edx, word ptr [rcx]
	WORD $0xc221             // ANDL AX, DX                          // and	edx, eax
	JNE  LBB3_27             // <--                                  // jne	.LBB3_27

LBB3_34:
	MOVQ $-0x1, AX      // <--                                  // mov	rax, -1
	NOP                 // (skipped)                            // mov	rsp, rbp
	NOP                 // (skipped)                            // pop	rbp
	VZEROUPPER          // <--                                  // vzeroupper
	MOVQ AX, ret+24(FP) // <--
	RET                 // <--                                  // ret

LBB3_35:
	LONG $0xc0dbf1c5 // VPAND X0, X1, X0                     // vpand	xmm0, xmm1, xmm0
	LONG $0xc9eff1c5 // VPXOR X1, X1, X1                     // vpxor	xmm1, xmm1, xmm1
	LONG $0xc174f9c5 // VPCMPEQB X1, X0, X0                  // vpcmpeqb	xmm0, xmm0, xmm1
	LONG $0xc0d7f9c5 // VPMOVMSKB X0, AX                     // vpmovmskb	eax, xmm0
	WORD $0xd0f7     // NOTL AX                              // not	eax
	SUBQ DI, CX      // <--                                  // sub	rcx, rdi

LBB3_31:
	LONG $0xc0bc0ff3    // TZCNT AX, AX                         // rep		bsf	eax, eax
	ADDQ CX, AX         // <--                                  // add	rax, rcx
	NOP                 // (skipped)                            // mov	rsp, rbp
	NOP                 // (skipped)                            // pop	rbp
	VZEROUPPER          // <--                                  // vzeroupper
	MOVQ AX, ret+24(FP) // <--
	RET                 // <--                                  // ret

LBB3_36:
	LONG $0xd8dbe5c5    // VPAND Y0, Y3, Y3                     // vpand	ymm3, ymm3, ymm0
	LONG $0xdc74e5c5    // VPCMPEQB Y4, Y3, Y3                  // vpcmpeqb	ymm3, ymm3, ymm4
	LONG $0xc3d7fdc5    // VPMOVMSKB Y3, AX                     // vpmovmskb	eax, ymm3
	CMPL AX, $-0x1      // <--                                  // cmp	eax, -1
	JE   LBB3_38        // <--                                  // je	.LBB3_38
	WORD $0xd0f7        // NOTL AX                              // not	eax
	LONG $0xc0bc0ff3    // TZCNT AX, AX                         // rep		bsf	eax, eax
	ADDQ CX, AX         // <--                                  // add	rax, rcx
	ADDQ $0x20, AX      // <--                                  // add	rax, 32
	NOP                 // (skipped)                            // mov	rsp, rbp
	NOP                 // (skipped)                            // pop	rbp
	VZEROUPPER          // <--                                  // vzeroupper
	MOVQ AX, ret+24(FP) // <--
	RET                 // <--                                  // ret

LBB3_38:
	LONG $0xd8dbedc5    // VPAND Y0, Y2, Y3                     // vpand	ymm3, ymm2, ymm0
	LONG $0xd2efe9c5    // VPXOR X2, X2, X2                     // vpxor	xmm2, xmm2, xmm2
	LONG $0xda74e5c5    // VPCMPEQB Y2, Y3, Y3                  // vpcmpeqb	ymm3, ymm3, ymm2
	LONG $0xc3d7fdc5    // VPMOVMSKB Y3, AX                     // vpmovmskb	eax, ymm3
	CMPL AX, $-0x1      // <--                                  // cmp	eax, -1
	JE   LBB3_40        // <--                                  // je	.LBB3_40
	WORD $0xd0f7        // NOTL AX                              // not	eax
	LONG $0xc0bc0ff3    // TZCNT AX, AX                         // rep		bsf	eax, eax
	ADDQ CX, AX         // <--                                  // add	rax, rcx
	ADDQ $0x40, AX      // <--                                  // add	rax, 64
	NOP                 // (skipped)                            // mov	rsp, rbp
	NOP                 // (skipped)                            // pop	rbp
	VZEROUPPER          // <--                                  // vzeroupper
	MOVQ AX, ret+24(FP) // <--
	RET                 // <--                                  // ret

LBB3_40:
	LONG $0xc0dbf5c5    // VPAND Y0, Y1, Y0                     // vpand	ymm0, ymm1, ymm0
	LONG $0xc274fdc5    // VPCMPEQB Y2, Y0, Y0                  // vpcmpeqb	ymm0, ymm0, ymm2
	LONG $0xc0d7fdc5    // VPMOVMSKB Y0, AX                     // vpmovmskb	eax, ymm0
	WORD $0xd0f7        // NOTL AX                              // not	eax
	LONG $0xc0bc0ff3    // TZCNT AX, AX                         // rep		bsf	eax, eax
	ADDQ CX, AX         // <--                                  // add	rax, rcx
	ADDQ $0x60, AX      // <--                                  // add	rax, 96
	NOP                 // (skipped)                            // mov	rsp, rbp
	NOP                 // (skipped)                            // pop	rbp
	VZEROUPPER          // <--                                  // vzeroupper
	MOVQ AX, ret+24(FP) // <--
	RET                 // <--                                  // ret
