//go:build !noasm && amd64
// Code generated by gocc -- DO NOT EDIT.

package ascii


//go:noescape
func isAsciiAvx(src string) bool

//go:noescape
func indexAnyAvxBitset(data string, bitset0 uint64, bitset1 uint64, bitset2 uint64, bitset3 uint64) int

//go:noescape
func equalFoldAvx(a string, b string) bool

//go:noescape
func indexMaskAvx(data string, mask byte) int

//go:noescape
func indexFoldRabinKarpAvx(a string, b string) int

//go:noescape
func indexFoldAvx(a string, b string) int
